[package]
name = "mini_gameserver"
version = "0.1.0"
authors = ["kerlw"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
websocket = "0.24.0"
